@startjson
#highlight "employer_id"
#highlight "employee_id"
#highlight "employee_id" / "id"
#highlight "employer_id" / "id"
{
    "Referral" : "",
    "employer_id" : {
        "Employer" : "",
        "id" : "varchar",
        "pk" : "varchar",
        "company_name" : "varchar",        
        "first_name" : "varchar",
        "middle_name" : "varchar",
        "last_name"  : "varchar",
        "phone_num" : "varchar",
        "email" : "varchar"
    },
    "message" : "varchar",
    "signature" : "varchar",
    "employee_id" : {
        "Employee" : "",
        "id" : "varchar",   
        "pk" : "varchar",
        "first_name" : "varchar",
        "middle_name" : "varchar",
        "last_name"  : "varchar",
        "phone_num" : "varchar",
        "email" : "varchar",
        "rui" : "float",        
        "referrals_num" : "int",
        "last_updated" : "timestamp"
    },
    "s_work_time" : "int",
    "s_pressure" : "int",
    "s_ethic" : "int",
    "s_complaints" : "int",
    "s_respect" : "int",
    "s_reliable" : "int",
    "s_task_time" : "int",
    "s_task_complete" : "int",
    "s_task_communicate" : "int",
    "s_task_experience" : "int",
    "s_fulltime" : "int"
}
@endjson
